### ISSUE TITLE
[Feature] Dashboard for the CNPG control plane metrics

### ISSUE THREAD

**Issue by danielloader** [cloudnative-pg/grafana-dashboards#13]
Hey, loving the dashboard for the cluster podMonitor outputs, works a treat.

Wondered if there was a dashboard available for the metrics emitted by the cloudnativePG controller itself?

**Comment by itay-grudev** [comment]
There are some automated healthchecks and metrics for the operator at the bottom of the dashboard. 

What now would you like to see?

**Comment by danielloader** [comment]
That's perfect I didn't even seen them down there. Thanks again.
