### ISSUE TITLE
[Bug] CPU and Memory not showing on the dashboard

### ISSUE THREAD

**Issue by danielloader** [cloudnative-pg/grafana-dashboards#14]
Showing missing request:

<img width="593" alt="image" src="https://github.com/user-attachments/assets/022f07da-9d60-4c7e-a55c-96da1809c889">

On exploring the query itself:

<img width="1134" alt="image" src="https://github.com/user-attachments/assets/87f3d452-9364-4a52-aa81-d5e5a7a57b49">

Can answer any questions to get to the bottom of this.

Thanks

**Comment by danielloader** [comment]
<img width="631" alt="image" src="https://github.com/user-attachments/assets/db656979-d8d8-4384-bc75-9605e580f9bf">
Noticed it's present in the screenshot on the [grafana dashboard market](https://grafana.com/grafana/dashboards/20417-cloudnativepg/) so guessing it's not just me then.

**Comment by itay-grudev** [comment]
Those are calculated as a percentage of the value from the `resources.requests.cpu`. If one is not set, you see the missing request message. Below that, you can see an absolute value, but not a relative percentage as it's not relevant in this case. 

It's strongly recommended you set both resources and limits, and you set both to the same value to ensure you get a `Guaranteed` QoS.

**Comment by danielloader** [comment]
Thanks for the help

**Comment by bab5470** [comment]
@itay-grudev We're having the same issue - we were missing resource request limit's but have now added them and applied via kubectl apply -f 

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

How long after adding them should data start showing up? I've set the interval to 5 minutes and waited way longer than 5 minutes. And its still showing: "Missing Request"

Guarantee QoS is not set—I see you mention that it is strongly recommended—but is it required for the graphs to work?

**Comment by itay-grudev** [comment]
Can you edit the panel and ensure the underlying metrics are reported? Did you install the `kube-prometheus-stack` helm chart that includes all the necessary component to export the Kuberneted information to Prometheus?
