### ISSUE TITLE
[Bug] CPU and Memory not showing on the dashboard 

### ISSUE THREAD

**Issue by bab5470** [cloudnative-pg/grafana-dashboards#21]
We're having the same issue as this person: https://github.com/cloudnative-pg/grafana-dashboards/issues/14

The response mentions:
```
Those [graphs] are calculated as a percentage of the value from the resources.requests.cpu. If one is not set, you see the missing request message. Below that, you can see an absolute value, but not a relative percentage as it's not relevant in this case.

It's strongly recommended you set both resources and limits, and you set both to the same value to ensure you get a Guaranteed QoS.
```

We do have resource limits set, but this is still not working:

```
  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"
```

Are we doing something wrong? I copied and pasted these resource limits directly from the documentation here:  https://cloudnative-pg.io/documentation/1.20/samples/cluster-example-full.yaml. 

Also, apologies for double posting. I was unclear if responding to a closed bug report or opening a new bug report was the best option, so I did both. I can delete one or the other, depending on which is preferred.

Thanks
Brad

**Comment by bab5470** [comment]
I think I may have this working. 

For the CPU metric I had to make the following changes to the promql query:

From:
```
sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="$namespace", pod=~"$instances"}) / sum(kube_pod_container_resource_requests{job="kube-state-metrics",  namespace="$namespace", resource="cpu", pod=~"$instances"})
```

To:
```
sum(rate(container_cpu_usage_seconds_total{namespace="$namespace", pod=~"$instances"}[1m]))/ sum(kube_pod_container_resource_requests{job="prometheus-kube-state-metrics",  namespace="$namespace", resource="cpu", pod=~"$instances"})
```

job="kube-state-metrics" seems to be job="prometheus-kube-state-metrics" on my environment - I don't know why. GPT says "The Prometheus Community Helm Chart for kube-state-metrics often uses the prometheus-kube-state-metrics job name, while a standalone installation might use kube-state-metrics."

Also, on my system, node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate doesn't seem to work. I have to use sum(rate(container_cpu_usage_seconds_total{namespace="$namespace", pod=~"$instances"}[1m]))

In fact any equation with `sum_irate` doesn't work. :-\ 


For the memory I had to make the following changes:

From: 
```
sum(container_memory_working_set_bytes{job="kubelet", metrics_path="/metrics/cadvisor", namespace="$namespace",container!="", image!="", pod=~"$instances"}) / sum(max by(pod) (kube_pod_container_resource_requests{job="kube-state-metrics", namespace="$namespace", resource="memory", pod=~"$instances"}))
```

To:
```
sum(container_memory_working_set_bytes{job="kubelet", namespace="$namespace",container!="", image!="", pod=~"$instances"}) / sum(max by(pod) (kube_pod_container_resource_requests{job="prometheus-kube-state-metrics", namespace="$namespace", resource="memory", pod=~"$instances"}))
```

I had to remove metrics_path="/metrics/cadvisor" and I had to change `kube-state-metrics` to `prometheus-kube-state-metrics` again

Maybe I missed it somewhere, but I don't see any mention of kube-state-metrics being required, nor do I see any references to cadvisor being required. These are certainly common in a Kubernetes environment, but it would be nice if this were mentioned somewhere, like the readme file. 

I'd certainly appreciate input from someone more experienced than me to validate that the above changes are correct and reasonable. They seem to result in reasonable and expected values, but I'm a Grafana/Prometheus/Promql newbie, so take the query changes above with a lump of salt.

**Comment by itay-grudev** [comment]
Make sure you specify the following parameters in your kube-prometheus-stack installation:

```yaml
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
```

**Comment by itay-grudev** [comment]
I really cannot debug what is missing or why in your cluster and/or `kube-prometheus-stack` installation. That being said should you be able to diagnose it yourself and identify an actual problem with the dashboard, I'll patch it.

**Comment by alexklibisz** [comment]
I'm hitting this same issue. It seems like `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate` is a custom recording rule that might not be provisioned in every prometheus deployment.

**Comment by alexklibisz** [comment]
I got the panels showing up with the following changes:

```diff
diff --git a/charts/cluster/grafana-dashboard.json b/charts/cluster/grafana-dashboard.json
index e96097e..7e9108b 100644
--- a/charts/cluster/grafana-dashboard.json
+++ b/charts/cluster/grafana-dashboard.json
@@ -847,7 +847,7 @@
             "uid": "${DS_PROMETHEUS}"
           },
           "editorMode": "code",
-          "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$instances\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",  namespace=\"$namespace\", resource=\"cpu\", pod=~\"$instances\"})",
+          "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$instances\"}[5m])) / \nsum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\", pod=~\"$instances\"})",
           "format": "time_series",
           "instant": true,
           "intervalFactor": 2,
@@ -1437,7 +1437,7 @@
             "uid": "${DS_PROMETHEUS}"
           },
           "editorMode": "code",
-          "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace\", pod=~\"$instances\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\", pod=~\"$instances\"}))",
+          "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$instances\"}[5m])) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\", pod=~\"$instances\"})",
           "hide": false,
           "legendFormat": "CPU",
           "range": true,
@@ -2496,7 +2496,7 @@
           },
           "editorMode": "code",
           "exemplar": true,
-          "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$instances\"})",
+          "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$instances\"}[5m]))",
           "hide": false,
           "interval": "",
           "legendFormat": "Total",
@@ -5026,7 +5026,7 @@
             "uid": "${DS_PROMETHEUS}"
           },
           "exemplar": true,
-          "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$instances\", namespace=~\"$namespace\"}) by (pod)",
+          "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$instances\", namespace=~\"$namespace\"}[5m])) by (pod) ",
           "format": "time_series",
           "interval": "",
           "intervalFactor": 2,
@@ -9186,4 +9186,4 @@
   "uid": "cloudnative-pg",
   "version": 2,
   "weekStart": ""
-}
+}
\ No newline at end of file

```

**Comment by itay-grudev** [comment]
I see. That makes sense. We can do that.
