### ISSUE TITLE
The ConfigMap "test-cnp-dashboard" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/grafana-dashboards#3]
I used to put the dashboard json file into a ConfigMap 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cnp-dashboard
  labels:
    grafana_dashboard: "1"
data:
  cnp.json: |-
    {
      "annotations": {
...
```

the new file is to big, when applying the ConfigMap, I get this error
```
$ k apply -f grafana-configmap.yaml
The ConfigMap "test-cnp-dashboard" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Comment by itay-grudev** [comment]
This error doesn't make sense. 

That number is `256kb`. According to the [documentation](https://kubernetes.io/docs/concepts/configuration/configmap/) the maximum size for a ConfigMap is `1 MiB`. The size of the `grafana-dashboard.json` is `248 KiB`.

Also the error says: `invalid: metadata.annotations`.

**Comment by itay-grudev** [comment]
The `invalid: metadata.annotations` apparently is not about the size of the `ConfigMap` contents, but about the size of the `last-applied-configuration` annotation, which `kubectl apply` adds.

See https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#how-to-create-objects.

Can you try:

```bash
kubectl create -f grafana-configmap.yaml
```

**Comment by smiyc** [comment]
```
$ kubectl replace -f grafana-configmap\ copy.yaml 
configmap/test-cnp-dashboard replaced
```
did the trick, thx for the hint @itay-grudev
