### ISSUE TITLE
hitting secrets too long when install using terraform. 

### ISSUE THREAD

**Issue by xiaolongkipsi** [cloudnative-pg/grafana-dashboards#4]
resource "helm_release" "grafana-dashboard" {
  name       = "postgres-grafana-dashboard"
  repository = "https://cloudnative-pg.github.io/grafana-dashboards"
  chart      = "cluster"
  version    = "0.0.1"
}

Error: create: failed to create: Secret "sh.helm.release.v1.postgres-grafana-dashboard.v1" is invalid: data: Too long: must have at most 1048576 bytes

**Comment by itay-grudev** [comment]
We just created a release `0.0.2`. Do you mind giving that a try?
